### ISSUE TITLE
Extract does not pull interpolation tags into yml file

### ISSUE THREAD

**Issue by alexabbott** [tsvetomir/xlf-extract#3]
When attempting to extract i18n messages that include a variable, the interpolation tags are removed and not inserted into the yml.

`<source>Test <x id="INTERPOLATION" equiv-text="{{ hello }}"/></source>
`

in the yaml file it becomes:
`Test
`

when it should be:
`Test <x id="INTERPOLATION" equiv-text="{{ hello }}"/>`

**Comment by tsvetomir** [comment]
Thanks for the bug report! Should be fixed in v0.2.1
